config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  root to: 'user/homes#top'


  scope module: :user do
    get 'reviews/search' => 'reviews#search'
    get 'reviews/bookmarks' => 'users#bookmarks'
    resources :reviews do
      resources :review_comments, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
    end
    get 'users/quit' => 'users#quit'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update]do
      get :bookmarks, on: :member
    end
  end

  namespace :admin do
    get 'homes/top'
    get 'reviews/search' => 'reviews#search'
    resources :users, only: [:index, :show, :edit, :update]
    resources :origins, only: [:index, :create, :edit, :update, :destroy]
    resources :types, only: [:index, :create, :edit, :update, :destroy]
    resources :brands, only: [:index, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy] do
      resources :review_comments, only: [:destroy]
    end
  end


  # scope module: :user do
  #   get 'users/quit' => 'users#quit'
  #   patch 'users/withdraw' => 'users#withdraw'
  #   resources :users, only: [:show, :edit, :update]do
  #     get :bookmarks, on: :member
  #   end
  # end

   # ゲストユーザー用のルーティング
  devise_scope :user do
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

end

app/models/brand.rb
class Brand < ApplicationRecord
  # 1つのブランドから複数商品が、ブランドが消えたら紐付く商品も消える
  has_many :products, dependent: :destroy

  # 空で登録だめ、一意性持たせる
  validates :name, presence: true, uniqueness: true

end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @brand = Brand.new
    @brands = Brand.all.page(params[:page]).per(10)
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      flash[:notice] = "登録が完了いたしました"
      redirect_to admin_brands_path
    else
    # エラーの場合一覧に戻る
      @brands = Brand.all.page(params[:page]).per(10)
      render :index
    end

  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update(brand_params)
      flash[:notice] = "変更が完了いたしました"
    # 変更後一覧画面にリダイレクト
      redirect_to admin_brands_path
    else
      # エラーの場合編集画面に戻る
      render :edit
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy
    flash[:notice] = "削除しました"
    redirect_to  admin_brands_path
  end


  def brand_params
    params.require(:brand).permit(:name)
  end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/views/admin/brands/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <h5 class="border p-3 my-3">
      ブランド編集
    </h5>
  </div>
  <br>
  <div class="row d-flex justify-content-center">
    <%= render "layouts/errors", obj: @brand %>
  </div>

  <div class="row d-flex justify-content-center my-3">
    <%= form_with model: @brand, url: admin_brand_path(@brand), method: :patch do |f| %>
      <div class="row d-flex justify-content-center">
        <div class="mr-3">
          <%= f.label :name, "ブランド名", class: "mr-3" %>
        </div>
        <div class="mr-5">
          <%= f.text_field :name, class: "rounded" %>
        </div>
        <div>
          <%= f.submit "変更", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/brands/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <h5 class="border-bottom p-3 my-3">
      ブランド一覧・追加
    </h5>
  </div>  
  <%= render "layouts/errors", obj: @brand %>
  <div class="row d-flex justify-content-center my-3">
    <%= form_with model: @brand, url: admin_brands_path, method: :post do |f| %>
      <div class="row d-flex justify-content-center">
        <div class="mr-3">
          <%= f.label :name, "ブランド名", class: "mr-3" %>
        </div>
        <div class="mr-5">
          <%= f.text_field :name, placeholder: "ブランド名", class: "rounded" %>
        </div>
        <div>
          <%= f.submit '新規登録', class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row d-flex justify-content-center">
    <div class="pull-left">
      <table class="table">
        <thead>
          <tr class="table-secondary">
            <th>ブランド</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @brands.each do |brand| %>
            <tr>
              <td><%= brand.name %></td>
              <td></td>
              <td><%= link_to "編集", edit_admin_brand_path(brand.id), class: "btn btn-success" %></td>
              <td><%= link_to "削除", admin_brand_path(brand.id), method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @brands, theme: 'bootstrap-5'%>
  </div>
</div>