config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  root to: 'user/homes#top'


  scope module: :user do
    get 'reviews/search' => 'reviews#search'
    get 'reviews/bookmarks' => 'users#bookmarks'
    resources :reviews do
      resources :review_comments, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
    end
    get 'users/quit' => 'users#quit'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update]do
      get :bookmarks, on: :member
    end
  end

  namespace :admin do
    get 'homes/top'
    get 'reviews/search' => 'reviews#search'
    resources :users, only: [:index, :show, :edit, :update]
    resources :origins, only: [:index, :create, :edit, :update, :destroy]
    resources :types, only: [:index, :create, :edit, :update, :destroy]
    resources :brands, only: [:index, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy] do
      resources :review_comments, only: [:destroy]
    end
  end


  # scope module: :user do
  #   get 'users/quit' => 'users#quit'
  #   patch 'users/withdraw' => 'users#withdraw'
  #   resources :users, only: [:show, :edit, :update]do
  #     get :bookmarks, on: :member
  #   end
  # end

   # ゲストユーザー用のルーティング
  devise_scope :user do
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:tag_name]
      @tag = Tag.find_by(name: params[:tag_name])
      @reviews = @tag.reviews.order(created_at: :desc).page(params[:page]).per(6)
    else
      @reviews = Review.order(created_at: :desc).page(params[:page]).per(6)
    end
    @tag_list = Tag.all
  end  
  
  def show
    @review = Review.find(params[:id])
    @review_comment = ReviewComment.new
    @review_tags = @review.tags
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "ユーザーの投稿を削除しました"
    redirect_to admin_reviews_path
  end

  def search
    @reviews = Review.where(product_id: params[:search][:product]).order(created_at: :desc).page(params[:page]).per(6)
    render :index
  end
  
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  # edit,update,destroyアクション前にensure_correct_user実行
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
 # ユーザーと紐付けしてるから誰が投稿したかの情報も一緒に入れてあげる
    @review.user_id = current_user.id
    # 受け取った値を,で区切って配列にする
    tag_list = params[:review][:name].split(',')
  # 保存できたらレビュー詳細へ
    if @review.save
      @review.save_tag(tag_list)
      redirect_to review_path(@review.id), notice: "投稿が完了しました"
    else
      render :new
    end
  end

  def index
    # paramsにtag_nameが含まれているときそのtagがついてるレビューを表示
    if params[:tag_name]
      @tag = Tag.find_by(name: params[:tag_name])
      @reviews = @tag.reviews.order(created_at: :desc).page(params[:page]).per(6)
    else
      @reviews = Review.order(created_at: :desc).page(params[:page]).per(6)
    end
    @tag_list = Tag.all
  end

  def show
    @review = Review.find(params[:id])
    @review_comment = ReviewComment.new
    @review_tags = @review.tags
  end

  def edit
    # pluckはmapと同じ意味
    @tag_list = @review.tags.pluck(:name).join(',')
  end

  def update
    tag_list = params[:review][:name].split(',')
    if @review.update(review_params)
      @review.save_tag(tag_list)
      redirect_to review_path(@review.id), notice: "投稿内容を変更しました"
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to user_path(@user)
  end

  def search
    @reviews = Review.where(product_id: params[:search][:product]).order(created_at: :desc).page(params[:page]).per(6)
    render :index
  end

  private
  def review_params
    params.require(:review).permit(:user_id, :product_id, :rate, :image, :body)
  end

  # 他人のreview編集画面へのアクセス禁止
  # 勝手に編集、削除しようとする人はTOPページへ行く
  def ensure_correct_user
    @review = Review.find(params[:id])
    @user = current_user
    unless @review.user == @user
      flash[:alert] = "他ユーザーの投稿は編集・削除できません。"
      redirect_to root_path
    end
  end

end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<div class="container">
  <div class="mt-4 mb-4">
    <h4>みんなのレビューチョコ
    <% if @tag.present? %>
    <i class="fa-sharp fa-solid fa-tag"></i>
      <%= @tag.name %>
      (全<%= @tag.reviews.count %>件)
    <% end %>
    </h4>

    <div class="my-3">
    <%= form_tag(admin_reviews_search_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
      <%= collection_select(:search, :product, Product.all, :id, :name, { prompt: '選択してください' }, class: "form-control mr-sm-2") %>
      <%= button_tag(type: 'submit', class: 'btn btn-primary my-2 my-sm-0') do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
    </div>
  </div>


  <% @reviews.each do |review| %>
    <div class="row my-3">
      <div class="col-sm-2">
        <%= image_tag review.get_image(200, 200), style: "width:100%;" %>
      </div>
      <div class="col-sm-10">
        <div class="row">
          <div class="col-md-6">
            <%= review.product.name %>
          </div>
          <div class="col-md-6 d-flex">
            <span class="mr-2"><%= review.rate %>点</span>
            <%= render "user/reviews/static_rate", review: review %>
          </div>
        </div>
        <div>
          user: <%= link_to review.user.name , user_path(review.user.id) %>
        </div>
        <div>
          review: <%= truncate(review.body, length: 23) %>
          <%= link_to ">> Read more", admin_review_path(review.id) %>
        </div>

        <% review.tags.each do |tag| %>
          <i class="fa-sharp fa-solid fa-tag"></i>
          <%= link_to tag.name, admin_reviews_path(tag_name: tag.name) %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="d-flex justify-content-center">
    <%= paginate @reviews, theme: 'bootstrap-5'%>
  </div>
</div>

app/views/admin/reviews/show.html.erb
<div class="container">
  <div class="row mt-4">
    <h4>レビュー詳細</h4>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @review.get_image(300, 300) %>
    </div>
    <div class="col-md-6">
                <!--投稿日-->
      <div><%= @review.created_at.strftime('%Y/%m/%d') %></div>
            <!-- ブックマーク（ログインしてなかったら非表示） -->
      <% if user_signed_in? %>
        <div id="bookmark_btn_<%= @review.id %>" class="text-right">
          <%= render "bookmark", review: @review %>
        </div>
      <% end %>
      <h5 class="product-name"><%= @review.product.name %></h5>
      <!--星評価-->
      <div class="d-flex align-items-center">
        <%= render "user/reviews/static_rate", review: @review %>
        <span class="ml-2 rate-styled"><%= @review.rate %></span>
      </div>
      <ul>
        <li>ブランド：
          <%= @review.product.brand.name %>
        </li>
        <li>価格：
          <%= @review.product.price %>円（店舗により異なります）
        </li>
        <li>種類：
          <%= @review.product.type.name %>
        </li>
        <li>産地：
          <%= @review.product.origin.name %>
        </li>
        <li>タグ：
          <% @review_tags.each do |tag| %>
          <i class="fa-sharp fa-solid fa-tag"></i>
            <%= link_to tag.name, admin_reviews_path(tag_name: tag.name) %>
          <% end %>
        </li>
      </ul>    
      <h6>～ レビュー ～</h6>
      <div><%= @review.body %></div>
    </div>
  </div>
  <div class="row mt-4 mb-4">
    <div class="col-md-6">
      <%=link_to user_path(@review.user.id) do  %>
        <div><%= image_tag @review.user.get_profile_image(150,150),class: "img-fluid rounded-circle"%></div>
        <div>user: <%= @review.user.name %></div>
      <% end %>  
    </div>
    <div class="col-md-6">
        <%= link_to "レビューを削除", admin_review_path(@review), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
        <%= link_to "会員詳細へ", admin_user_path(@review.user.id), class: "btn btn-sm btn-outline-primary ml-3"%>
    </div>
  </div>

  <div class="card"> 
    <div class="card-body">
      <!-- コメント件数 -->
      <p>コメント件数：<span id="comment_count"><%= @review.review_comments.count %></span></p>
      <div id="review-comments">
        <!--コメント一覧-->
        <%= render "admin/review_comments/index", review: @review %>
      </div>
    </div>
  </div>
</div>