config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  root to: 'user/homes#top'


  scope module: :user do
    get 'reviews/search' => 'reviews#search'
    get 'reviews/bookmarks' => 'users#bookmarks'
    resources :reviews do
      resources :review_comments, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
    end
    get 'users/quit' => 'users#quit'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update]do
      get :bookmarks, on: :member
    end
  end

  namespace :admin do
    get 'homes/top'
    get 'reviews/search' => 'reviews#search'
    resources :users, only: [:index, :show, :edit, :update]
    resources :origins, only: [:index, :create, :edit, :update, :destroy]
    resources :types, only: [:index, :create, :edit, :update, :destroy]
    resources :brands, only: [:index, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy] do
      resources :review_comments, only: [:destroy]
    end
  end


  # scope module: :user do
  #   get 'users/quit' => 'users#quit'
  #   patch 'users/withdraw' => 'users#withdraw'
  #   resources :users, only: [:show, :edit, :update]do
  #     get :bookmarks, on: :member
  #   end
  # end

   # ゲストユーザー用のルーティング
  devise_scope :user do
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ユーザー1人につき1つのプロフィール画像
  has_one_attached :profile_image
  # 1人のユーザーは複数のレビューを投稿できる、ユーザーが消えたらそのレビューも消える
  has_many :reviews, dependent: :destroy
  # 1人のユーザーは複数コメントできる、ユーザーが消えたらそのコメントも消える
  has_many :review_comments, dependent: :destroy
  # ユーザーは複数のレビューをブックマークできる、ユーザーが消えたらそのブックマークも消える
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_reviews, through: :bookmarks, source: :review
  # 空で登録できない
  validates :name, presence: true

  # ゲストユーザーのメールアドレス
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.bio = "これはゲストユーザーです"
    end
  end

  # メールアドレスがゲストユーザーのものであるかの判定
  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def active_for_authentication?
    super && is_active # ユーザーがログインするためには、active?がtrueを返すことも必要
  end


  # プロフィールイメージの設定(呼び出すとき引数必要!)
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(gravity: :center, resize:"#{width}x#{height}^", crop:"#{width}x#{height}+0+0").processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "変更が完了しました"
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :email, :is_active)
  end


end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)
    @review = @bookmark.review
    if @bookmark.valid?
      @bookmark.save
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @review = @bookmark.review
    @bookmark.destroy
  end

  private

  def bookmark_params
    params.permit(:review_id)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  # 最新レビュー4つ表示
  def top
    @reviews = Review.order('id DESC').limit(4)
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController

  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/review_comments_controller.rb
class User::ReviewCommentsController < ApplicationController
  # destroyアクション前にensure_correct_user実行
  before_action :ensure_correct_user, only: [:destroy]
  before_action :authenticate_user!, only: [:destroy]

  def create
    @review = Review.find(params[:review_id])
    comment = current_user.review_comments.new(review_comment_params)
    comment.review_id = @review.id
    comment.save

  end


  def destroy
    @review_comment = ReviewComment.find(params[:id])
    @review_comment.destroy

  end

  private

  def review_comment_params
    params.require(:review_comment).permit(:comment)
  end

  # 他人のreview編集画面へのアクセス禁止
  # 勝手に編集、削除しようとする人はTOPページへ行く
  def ensure_correct_user
    @review = Review.find(params[:review_id])
    @user = current_user
    unless @review.user == @user
      flash[:alert] = "他ユーザーのコメントは削除できません。"
      redirect_to root_path
    end
  end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  # edit,update,destroyアクション前にensure_correct_user実行
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
 # ユーザーと紐付けしてるから誰が投稿したかの情報も一緒に入れてあげる
    @review.user_id = current_user.id
    # 受け取った値を,で区切って配列にする
    tag_list = params[:review][:name].split(',')
  # 保存できたらレビュー詳細へ
    if @review.save
      @review.save_tag(tag_list)
      redirect_to review_path(@review.id), notice: "投稿が完了しました"
    else
      render :new
    end
  end

  def index
    # paramsにtag_nameが含まれているときそのtagがついてるレビューを表示
    if params[:tag_name]
      @tag = Tag.find_by(name: params[:tag_name])
      @reviews = @tag.reviews.order(created_at: :desc).page(params[:page]).per(6)
    else
      @reviews = Review.order(created_at: :desc).page(params[:page]).per(6)
    end
    @tag_list = Tag.all
  end

  def show
    @review = Review.find(params[:id])
    @review_comment = ReviewComment.new
    @review_tags = @review.tags
  end

  def edit
    # pluckはmapと同じ意味
    @tag_list = @review.tags.pluck(:name).join(',')
  end

  def update
    tag_list = params[:review][:name].split(',')
    if @review.update(review_params)
      @review.save_tag(tag_list)
      redirect_to review_path(@review.id), notice: "投稿内容を変更しました"
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to user_path(@user)
  end

  def search
    @reviews = Review.where(product_id: params[:search][:product]).order(created_at: :desc).page(params[:page]).per(6)
    render :index
  end

  private
  def review_params
    params.require(:review).permit(:user_id, :product_id, :rate, :image, :body)
  end

  # 他人のreview編集画面へのアクセス禁止
  # 勝手に編集、削除しようとする人はTOPページへ行く
  def ensure_correct_user
    @review = Review.find(params[:id])
    @user = current_user
    unless @review.user == @user
      flash[:alert] = "他ユーザーの投稿は編集・削除できません。"
      redirect_to root_path
    end
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # ログイン機能のコントローラー
  before_action :user_state, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "guestuserでログインしました。"
  end


  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected
  # 退会しているかを判断するメソッド
  def user_state
    # 入力されたemailからアカウントを1件取得
    @user = User.find_by(email: params[:user][:email])
    if @user
    # 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
      if @user.valid_password?(params[:user][:password]) && !@user.is_active
      #一致してるかつ退会してたら（!〇〇.is_active=有効状態の反転）
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_path
      else
          flash[:notice] = "項目を入力してください"
      end
    end

  end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザー情報の変更を完了しました"
    else
      render :edit
    end
  end

  def bookmarks
    @user = User.find(current_user.id)
    @bookmark_reviews = @user.bookmarks.page(params[:page]).per(10)
  end

  def quit
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_active: false)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end


  private
  def user_params
    params.require(:user).permit(:name, :bio, :is_active, :email, :profile_image)
  end

  # 他人のユーザ情報編集画面にいけないようにするやつ
  # 勝手に編集しようとする人は自分のuser/showページへ行く
  def ensure_correct_user
    @user = User.find(params[:id])
    unless  @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  # ゲストユーザーはユーザ情報編集画面に遷移できない
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/bookmarks_helper.rb
module User::BookmarksHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/review_comments_helper.rb
module User::ReviewCommentsHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/bookmarks.html.erb
<div class="container">
  <div class="row mt-4">
    <h4>
      <%= @user.name %> さんのブックマーク一覧
    </h4>
  </div>
  <% @bookmark_reviews.each do |bookmark| %>
    <div class="row my-3">
      <div class="col-sm-2">
        <%= image_tag bookmark.review.get_image(200, 200), style: "width:100%;" %>
      </div>
      <div class="col-sm-10">
        <div class="row">
          <div class="col-md-6">
            <%= bookmark.review.product.name %>
          </div>
          <div class="col-md-6 d-flex">
            <span class="mr-2"><%= bookmark.review.rate %>点</span>
            <%= render "user/reviews/static_rate", review: bookmark.review %>
              <div id="bookmark_btn_<%= bookmark.review.id %>">
                <%= render "user/reviews/bookmark", review: bookmark.review %>
              </div>
          </div>
        </div>  
        <div>
          user: <%= link_to bookmark.review.user.name , user_path(bookmark.review.user.id) %>
        </div>
        <div>
          review: <%= truncate(bookmark.review.body, length: 23) %>
          <%= link_to ">> Read more", review_path(bookmark.review.id) %>
        </div>
        <% bookmark.review.tags.each do |tag| %>
          <i class="fa-sharp fa-solid fa-tag"></i>
          <%= link_to tag.name, reviews_path(tag_name: tag.name) %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="d-flex justify-content-center">
    <%= paginate @bookmark_reviews, theme: 'bootstrap-5' %>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "マイページに戻る", user_path(@user), class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/user/users/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="border p-4">
        <h4 class="text-center">マイページ管理</h4>
        <div class="row d-flex justify-content-center">
          <%= render "layouts/errors", obj: @user %>
        </div>

        <%= form_with model: @user do |f| %>
          <div class="form-group">
            <label for="user_name">ユーザーネーム</label>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <label for="user_profile_image">プロフィール画像</label><br>
            <%= f.file_field :profile_image, accept: "image/*" %>
          </div>

          <div class="form-group">
            <label for="user_bio">自己紹介</label>
            <%= f.text_area :bio, placeholder: "自己紹介文を入力", class: "form-control", rows: 5 %>
          </div>

          <div class="form-group">
            <label for="user_email">メールアドレス</label>
            <%= f.text_field :email, size: "45", placeholder: "メールアドレスを入力(choco＠chocomate.com)", autocomplete: "email", style: "height: 35px;", class: "form-control" %>
          </div>

          <div class="form-group text-center">
            <%= f.submit "登録情報を変更する", class: "btn btn-primary" %>
          </div>
        <% end %>
        <div class="text-center mt-3">
          退会手続きをする <%= link_to "こちらから", users_quit_path, class:"btn btn-danger mx-2" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/users/quit.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col px-0 offset-1">
       <div style="text-align: center">
        <h2>本当に退会しますか？</h2>
        <p>
          退会すると、会員登録情報やが閲覧できなくなります。<br>
          退会する場合は、「退会する」をクリックしてください。
        </p>
          <%= link_to "退会しない", user_path(current_user), :class => "btn btn-outline-primary ms-3" %>
          <%= link_to "退会する", users_withdraw_path, method: :patch, :class => "btn btn-danger ms-3", data: { confirm: "本当に退会しますか？" }  %>
        </div>
    </div>
  </div>
</div>

app/views/user/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <div class="mt-3 mb-2">
        <%= image_tag @user.get_profile_image(200, 200) ,class: "img-fluid rounded-circle" %>
      </div>  
    
      <div><strong>ユーザーネーム</strong></div>
      <div class="mb-2"> <%= @user.name %></div>
      <div><strong>自己紹介</strong></div>
      <div class="mb-2"><%= @user.bio %></div>
      <div class="mb-2">レビュー数：  <%= @user.reviews.count %></div>

    <% if current_user == @user %>
      <div class='row'>
        <% unless @user.guest_user? %>
          <%= link_to bookmarks_user_path(@user.id), class: "btn btn-secondary btn-block" do %>
            <i class="fas fa-bookmark"></i>
          <% end %>

          <%= link_to edit_user_path(@user.id), class: "btn btn-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        <% else %>
          <%= link_to bookmarks_user_path(@user.id), class: "btn btn-secondary btn-block" do %>
            <i class="fas fa-bookmark"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
    </div>
    <div class='col-md-8 offset-md-1 mt-3'>
      <h4><%= @user.name %> さんのレビュー</h4>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>商品名</th>
            <th>評価</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @reviews.each do |review| %>
            <tr>
              <td><%= image_tag review.get_image(150, 150) %></td>
              <td><%= review.product.name %></td>
              <td><%= render "user/reviews/static_rate", review: review %></td>
              <td>
              <% if review.user == current_user %>
                <span><%= link_to "編集", edit_review_path(review.id), class: "btn btn-sm btn-success" %>
                <%= link_to "削除", review_path(review.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></span>
              <% end %><br>
                <%= link_to ">> Read more", (admin_signed_in? ? admin_review_path(review.id) : review_path(review.id)) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>