config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  root to: 'user/homes#top'


  scope module: :user do
    get 'reviews/search' => 'reviews#search'
    get 'reviews/bookmarks' => 'users#bookmarks'
    resources :reviews do
      resources :review_comments, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
    end
    get 'users/quit' => 'users#quit'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update]do
      get :bookmarks, on: :member
    end
  end

  namespace :admin do
    get 'homes/top'
    get 'reviews/search' => 'reviews#search'
    resources :users, only: [:index, :show, :edit, :update]
    resources :origins, only: [:index, :create, :edit, :update, :destroy]
    resources :types, only: [:index, :create, :edit, :update, :destroy]
    resources :brands, only: [:index, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy] do
      resources :review_comments, only: [:destroy]
    end
  end


  # scope module: :user do
  #   get 'users/quit' => 'users#quit'
  #   patch 'users/withdraw' => 'users#withdraw'
  #   resources :users, only: [:show, :edit, :update]do
  #     get :bookmarks, on: :member
  #   end
  # end

   # ゲストユーザー用のルーティング
  devise_scope :user do
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ユーザー1人につき1つのプロフィール画像
  has_one_attached :profile_image
  # 1人のユーザーは複数のレビューを投稿できる、ユーザーが消えたらそのレビューも消える
  has_many :reviews, dependent: :destroy
  # 1人のユーザーは複数コメントできる、ユーザーが消えたらそのコメントも消える
  has_many :review_comments, dependent: :destroy
  # ユーザーは複数のレビューをブックマークできる、ユーザーが消えたらそのブックマークも消える
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_reviews, through: :bookmarks, source: :review
  # 空で登録できない
  validates :name, presence: true

  # ゲストユーザーのメールアドレス
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.bio = "これはゲストユーザーです"
    end
  end

  # メールアドレスがゲストユーザーのものであるかの判定
  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def active_for_authentication?
    super && is_active # ユーザーがログインするためには、active?がtrueを返すことも必要
  end


  # プロフィールイメージの設定(呼び出すとき引数必要!)
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(gravity: :center, resize:"#{width}x#{height}^", crop:"#{width}x#{height}+0+0").processed
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:tag_name]
      @tag = Tag.find_by(name: params[:tag_name])
      @reviews = @tag.reviews.order(created_at: :desc).page(params[:page]).per(6)
    else
      @reviews = Review.order(created_at: :desc).page(params[:page]).per(6)
    end
    @tag_list = Tag.all
  end  
  
  def show
    @review = Review.find(params[:id])
    @review_comment = ReviewComment.new
    @review_tags = @review.tags
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "ユーザーの投稿を削除しました"
    redirect_to admin_reviews_path
  end

  def search
    @reviews = Review.where(product_id: params[:search][:product]).order(created_at: :desc).page(params[:page]).per(6)
    render :index
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "変更が完了しました"
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :email, :is_active)
  end


end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)
    @review = @bookmark.review
    if @bookmark.valid?
      @bookmark.save
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @review = @bookmark.review
    @bookmark.destroy
  end

  private

  def bookmark_params
    params.permit(:review_id)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  # 最新レビュー4つ表示
  def top
    @reviews = Review.order('id DESC').limit(4)
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController

  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/review_comments_controller.rb
class User::ReviewCommentsController < ApplicationController
  # destroyアクション前にensure_correct_user実行
  before_action :ensure_correct_user, only: [:destroy]
  before_action :authenticate_user!, only: [:destroy]

  def create
    @review = Review.find(params[:review_id])
    comment = current_user.review_comments.new(review_comment_params)
    comment.review_id = @review.id
    comment.save

  end


  def destroy
    @review_comment = ReviewComment.find(params[:id])
    @review_comment.destroy

  end

  private

  def review_comment_params
    params.require(:review_comment).permit(:comment)
  end

  # 他人のreview編集画面へのアクセス禁止
  # 勝手に編集、削除しようとする人はTOPページへ行く
  def ensure_correct_user
    @review = Review.find(params[:review_id])
    @user = current_user
    unless @review.user == @user
      flash[:alert] = "他ユーザーのコメントは削除できません。"
      redirect_to root_path
    end
  end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  # edit,update,destroyアクション前にensure_correct_user実行
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
 # ユーザーと紐付けしてるから誰が投稿したかの情報も一緒に入れてあげる
    @review.user_id = current_user.id
    # 受け取った値を,で区切って配列にする
    tag_list = params[:review][:name].split(',')
  # 保存できたらレビュー詳細へ
    if @review.save
      @review.save_tag(tag_list)
      redirect_to review_path(@review.id), notice: "投稿が完了しました"
    else
      render :new
    end
  end

  def index
    # paramsにtag_nameが含まれているときそのtagがついてるレビューを表示
    if params[:tag_name]
      @tag = Tag.find_by(name: params[:tag_name])
      @reviews = @tag.reviews.order(created_at: :desc).page(params[:page]).per(6)
    else
      @reviews = Review.order(created_at: :desc).page(params[:page]).per(6)
    end
    @tag_list = Tag.all
  end

  def show
    @review = Review.find(params[:id])
    @review_comment = ReviewComment.new
    @review_tags = @review.tags
  end

  def edit
    # pluckはmapと同じ意味
    @tag_list = @review.tags.pluck(:name).join(',')
  end

  def update
    tag_list = params[:review][:name].split(',')
    if @review.update(review_params)
      @review.save_tag(tag_list)
      redirect_to review_path(@review.id), notice: "投稿内容を変更しました"
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to user_path(@user)
  end

  def search
    @reviews = Review.where(product_id: params[:search][:product]).order(created_at: :desc).page(params[:page]).per(6)
    render :index
  end

  private
  def review_params
    params.require(:review).permit(:user_id, :product_id, :rate, :image, :body)
  end

  # 他人のreview編集画面へのアクセス禁止
  # 勝手に編集、削除しようとする人はTOPページへ行く
  def ensure_correct_user
    @review = Review.find(params[:id])
    @user = current_user
    unless @review.user == @user
      flash[:alert] = "他ユーザーの投稿は編集・削除できません。"
      redirect_to root_path
    end
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # ログイン機能のコントローラー
  before_action :user_state, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "guestuserでログインしました。"
  end


  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected
  # 退会しているかを判断するメソッド
  def user_state
    # 入力されたemailからアカウントを1件取得
    @user = User.find_by(email: params[:user][:email])
    if @user
    # 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
      if @user.valid_password?(params[:user][:password]) && !@user.is_active
      #一致してるかつ退会してたら（!〇〇.is_active=有効状態の反転）
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_path
      else
          flash[:notice] = "項目を入力してください"
      end
    end

  end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザー情報の変更を完了しました"
    else
      render :edit
    end
  end

  def bookmarks
    @user = User.find(current_user.id)
    @bookmark_reviews = @user.bookmarks.page(params[:page]).per(10)
  end

  def quit
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_active: false)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end


  private
  def user_params
    params.require(:user).permit(:name, :bio, :is_active, :email, :profile_image)
  end

  # 他人のユーザ情報編集画面にいけないようにするやつ
  # 勝手に編集しようとする人は自分のuser/showページへ行く
  def ensure_correct_user
    @user = User.find(params[:id])
    unless  @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  # ゲストユーザーはユーザ情報編集画面に遷移できない
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
  
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/bookmarks_helper.rb
module User::BookmarksHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/review_comments_helper.rb
module User::ReviewCommentsHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/user/reviews/_bookmark.html.erb
<!--レビューしたユーザーがログインしたユーザーじゃなかったら-->
<% if current_user != review.user %>
  <% if review.find_bookmark(current_user).blank? %>
  <!-- ブックマーク登録 -->
    <%= link_to review_bookmarks_path(review), method: :post, remote: true do %>
      <i class="fa-regular fa-bookmark" style="font-size: 45px; color: #6a2f36;"></i>
    <% end %>
  <% else %>
  <!-- ブックマーク解除 -->
    <%= link_to review_bookmark_path(review, review.find_bookmark(current_user)), method: :delete, remote: true do %>
      <i class="fas fa-bookmark" style="font-size: 45px; color: #6a2f36;"></i>
    <% end %>
  <% end %>
<% end %>

app/views/user/reviews/_form.html.erb
<%= form_with model: @review do |f| %>
<%= render "layouts/errors", obj: @review %>
  <div>商品画像<span class="required-text">(必須)</span></div>
  <div>
    <%= f.file_field :image, accept: "image/*" %>
  </div>

  <div class="mt-2"><%= f.label :product_id,"商品" %></div>
  <div>
    <%= f.select :product_id, Product.all.map { |product| [product.name, product.id] } %>
  </div>
  <div class="mt-2">レビュー本文<span class="required-text">(必須)</span></div>
  <div class="mb-2">
    <%= f.text_area :body, size: "40x10" , placeholder: 'ここにレビューを入力してください（最大500文字）' %>
  </div>
  <!--タグ-->
  <div><%= f.label " タグ (,で区切ると複数タグ登録できます)" %></div>
  <div>
    <%= f.text_field :name, value: @tag_list,class: "form-control"%>
  </div>
  <!--星評価-->
  <% if @review.id.nil? %>
    <div class="form-group mt-2" id="star">
      <%= f.label :rate,"星評価(1.0～5.0)" %>
      <%= f.hidden_field :rate, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;

        elem.innerHTML = ""
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'review[rate]',
          half: true,
        };
        raty(elem, opt);
      });
    </script>
  <% else %>
    <div class="form-group">
      <%= render "static_rate", review: @review %>
    </div>
  <% end %>

  <div>
    <% if @review.new_record? %>
      <%= f.submit "レビューを投稿する", class:"btn btn-success" %>
    <% else %>
      <%= f.submit "レビューを編集する", class:"btn btn-success"  %>
    <% end %>
  </div>
<% end %>

app/views/user/reviews/_static_rate.html.erb
<div id="star_<%= review.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= review.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= review.rate %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/user/reviews/edit.html.erb
<div class="container">
  <div class="row mt-4 justify-content-center">
    <div class="col-md-12">
      <h4>レビュー編集</h4>
    </div>
  </div>  
  <div class="row mb-3 justify-content-center">
    <div class="col-md-12">
      <%= render "form", review: @review %>
    </div>
  </div>
</div>

app/views/user/reviews/index.html.erb
<div class="container">
  <div class="mt-4 mb-4">
    <h4>みんなのレビューチョコ
    <% if @tag.present? %>
    <i class="fa-sharp fa-solid fa-tag"></i>
      <%= @tag.name %>
      (全<%= @tag.reviews.count %>件)
    <% end %>
    </h4>

    <div class="my-3">
    <%= form_tag(reviews_search_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
      <%= collection_select(:search, :product, Product.all, :id, :name, { prompt: '選択してください' }, class: "form-control mr-sm-2") %>
      <%= button_tag(type: 'submit', class: 'btn btn-primary my-2 my-sm-0') do %>
        <i class="fas fa-search"></i> 
      <% end %>
    <% end %>
    </div>
  </div>

  <% @reviews.each do |review| %>
    <div class="row my-3">
      <div class="col-sm-2">
        <%= image_tag review.get_image(200, 200), style: "width:100%;" %>
      </div>
      <div class="col-sm-10">
        <div class="row">
          <div class="col-md-6">
            <%= review.product.name %>
          </div>
          <div class="col-md-6 d-flex">
            <span class="mr-2"><%= review.rate %>点</span>
            <%= render "static_rate", review: review %>
          </div>
        </div>
        <div>
          user: <%= link_to review.user.name , user_path(review.user.id) %>
        </div>
        <div>
          review: <%= truncate(review.body, length: 23) %>
          <%= link_to ">> Read more", review_path(review.id) %>
        </div>

        <% review.tags.each do |tag| %>
          <i class="fa-sharp fa-solid fa-tag"></i>
          <%= link_to tag.name, reviews_path(tag_name: tag.name) %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="d-flex justify-content-center">
    <%= paginate @reviews, theme: 'bootstrap-5'%>
  </div>
</div>

app/views/user/reviews/new.html.erb
<div class="container">
  <div class="row mt-4 justify-content-center">
    <div class="col-md-12">
      <h4>レビュー投稿</h4>
    </div>
  </div>  
  <div class="row mb-3 justify-content-center">
    <div class="col-md-12">
      <%= render "form", review: @review %>
    </div>
  </div>
</div>

app/views/user/reviews/show.html.erb
<div class="container mb-5">
  <div class="row mt-4">
    <h4>レビュー詳細</h4>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @review.get_image(300, 300) %>
    </div>
    <div class="col-md-6">
                <!--投稿日-->
      <div><%= @review.created_at.strftime('%Y/%m/%d') %></div>
            <!-- ブックマーク（ログインしてなかったら非表示） -->
      <% if user_signed_in? %>
        <div id="bookmark_btn_<%= @review.id %>" class="text-right">
          <%= render "bookmark", review: @review %>
        </div>
      <% end %>
      <h5 class="product-name"><%= @review.product.name %></h5>
      <!--星評価-->
      <div class="d-flex align-items-center">
        <%= render "static_rate", review: @review %>
        <span class="ml-2 rate-styled"><%= @review.rate %></span>
      </div>
      <ul>
        <li>ブランド：
          <%= @review.product.brand.name %>
        </li>
        <li>価格：
          <%= @review.product.price %>円（店舗により異なります）
        </li>
        <li>種類：
          <%= @review.product.type.name %>
        </li>
        <li>産地：
          <%= @review.product.origin.name %>
        </li>
        <li>タグ：
          <% @review_tags.each do |tag| %>
          <i class="fa-sharp fa-solid fa-tag"></i>
            <%= link_to tag.name, reviews_path(tag_name: tag.name) %>
          <% end %>
        </li>
      </ul>    
      <h6>～ レビュー ～</h6>
      <div><%= @review.body %></div>
    </div>
  </div>
  <div class="row mt-4 mb-4">
    <div class="col-md-6">
      <%= link_to user_path(@review.user.id) do  %>
          <%= image_tag @review.user.get_profile_image(150,150), class: "img-fluid rounded-circle" %><br>
          user: <%= @review.user.name %>
      <% end %>     
    </div>
    <div class="col-md-6">
      <% if @review.user == current_user %>
        <%= link_to "編集", edit_review_path, class: "btn btn-sm btn-success" %>
        <%= link_to "削除", review_path, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
      <% end %> 
    </div>
  </div>
  
  <div class="card"> 
    <div class="card-body">
        <!-- コメント件数 -->
      <p>コメント件数：<span id="comment_count"><%= @review.review_comments.count %></span></p>
      <div id="review-comments">
        <!--コメント一覧-->
        <%= render "user/review_comments/index", review: @review %>
      </div>
      <div id="post-comments">
        <!--コメント投稿フォーム(ログインしてなかったら非表示)-->
        <% if user_signed_in? %>
          <%= render "user/review_comments/form" , { review: @review , review_comment: @review_comment } %>
        <% end %>
      </div>
    </div>
  </div>
</div>